import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from 'next/headers';
import './globals.css';
import ThemeToggle from "@/components/ThemeToggle";
import { Providers } from '@/lib/providers';
import HomeButton from "@/components/HomeButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = (await cookies()).get('theme')?.value ?? 'light';
  const isDark = theme === 'dark';
  console.log('isDark', isDark);
  return (
    <html lang="en" className={isDark ? 'dark' : ''}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="absolute top-4 left-4 z-50">
            <HomeButton />
          </header>
          {children}
          <div className="fixed bottom-0 right-0 p-4">
            <ThemeToggle />
          </div>
        </Providers>
      </body>
    </html>
  );
}
